---

- name: "Apple tethering | {{ tethering_apple | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: if_ipheth_load
    state: "{{ tethering_apple | ternary('present', 'absent') }}"
    value: "YES"
    path: /boot/loader.conf

- name:
    "Android tethering | {{ tethering_android | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: if_urndis_load
    state: "{{ tethering_android | ternary('present', 'absent') }}"
    value: "YES"
    path: /boot/loader.conf

- name: "CDCE tethering | {{ tethering_cdce | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: if_cdce_load
    state: "{{ tethering_cdce | ternary('present', 'absent') }}"
    value: "YES"
    path: /boot/loader.conf

- name: Configure Apple devices
  ansible.builtin.blockinfile:
    path: /etc/devd.conf
    block: |
      notify 100 {
              match "system"          "USB";
              match "subsystem"       "DEVICE";
              match "type"            "ATTACH";
              match "vendor"          "0x05ac";
              match "product"         "0x12a8";
              action "usbconfig -d $cdev set_config 3";
      };
  when: tethering_apple

- name: Ensure devd directory exists
  ansible.builtin.file:
    path: /usr/local/etc/devd
    state: directory
    owner: root
    group: wheel
    mode: '0755'

- name: Configure ueX interface
  ansible.builtin.copy:
    src: usb_tethering.conf
    dest: /usr/local/etc/devd/usb_tethering.conf
    owner: root
    group: wheel
    mode: '0644'
