---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

  provision: false
  cachier: machine
  parallel: true

platforms:
  - name: instance
    box: "generic/${MOLECULE_DISTRO}"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp

    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", type: "rsync"'
      - 'vm.provision :shell, inline: "uname"'

    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: true

    memory: 512
    cpus: 1

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

  config_options:
    defaults:
      verbosity: ${MOLECULE_VERBOSITY:-2}

verifier:
  name: ansible
