---

argument_specs:
  main:
    short_description: Installs QMK
    description:
      - Deploy QMK source and tools.
      - QMK Firmware for keyboards using AVR and ARM processors.

    author:
      - charlesrocket

    options:
      qmk_github:
        description: Set GitHub username.
        type: str
        default: qmk
